// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyjwcpqyzeazqdgskfyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5andjcHF5emVhenFkZ3NrZnl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTA3MzMsImV4cCI6MjA3MzE4NjczM30.zMxq2SzgqBnLYyy-W-a_e53SUppSBlCQcT_26qoVIf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});